# Generated by Django 5.0.4 on 2024-04-07 06:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_power', models.IntegerField()),
                ('blue', models.IntegerField()),
                ('clock_speed', models.FloatField()),
                ('dual_sim', models.IntegerField()),
                ('fc', models.FloatField()),
                ('four_g', models.FloatField()),
                ('int_memory', models.FloatField()),
                ('m_dep', models.FloatField()),
                ('mobile_wt', models.FloatField()),
                ('n_cores', models.FloatField()),
                ('pc', models.FloatField()),
                ('px_height', models.FloatField()),
                ('px_width', models.FloatField()),
                ('ram', models.FloatField()),
                ('sc_h', models.FloatField()),
                ('sc_w', models.FloatField()),
                ('talk_time', models.IntegerField()),
                ('three_g', models.IntegerField()),
                ('touch_screen', models.IntegerField()),
                ('wifi', models.IntegerField()),
            ],
            options={
                'db_table': 'Device',
            },
        ),
    ]
